# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "Efortless time tracking in your terminal"
  homepage "https://github.com/TristanSch1/flow"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TristanSch1/flow/releases/download/v0.2.2/flow_Darwin_x86_64.tar.gz"
      sha256 "cbb01e7d9f9f0eb29fae0efde0b64bb38d4436363f6185f32484bf6589bcc92f"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TristanSch1/flow/releases/download/v0.2.2/flow_Darwin_arm64.tar.gz"
      sha256 "c781fdb77d0de59a60c8322eb74a0591c675bff56caaf837f09f9f0711466e8c"

      def install
        bin.install "flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TristanSch1/flow/releases/download/v0.2.2/flow_Linux_x86_64.tar.gz"
      sha256 "76eb5530d4ef9df015bee7f5432a273efcd8bb23430374796821a3d838fc4309"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TristanSch1/flow/releases/download/v0.2.2/flow_Linux_arm64.tar.gz"
      sha256 "4f2341b468ace774b76aa187bb01166d46f26c3c79ce046c99ee77b63217ceef"

      def install
        bin.install "flow"
      end
    end
  end
end
