# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowTracker < Formula
  desc "Efortless time tracking in your terminal"
  homepage "https://github.com/TristanSch1/flow"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TristanSch1/flow/releases/download/v1.0.1/flow_Darwin_x86_64.tar.gz"
      sha256 "b6c69b3d5a214eb902ad1c537e053244d2fc7e1e82978b96384eac3b288a6add"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TristanSch1/flow/releases/download/v1.0.1/flow_Darwin_arm64.tar.gz"
      sha256 "8caab28a66514d920f5de6463bc8776d42464ba7b49847cd9294ff864f01d062"

      def install
        bin.install "flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TristanSch1/flow/releases/download/v1.0.1/flow_Linux_x86_64.tar.gz"
      sha256 "9a09a60f41676080499e2f64c38f37be6befa06a6fb8eb0a5d79c8f9bd2dab8e"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TristanSch1/flow/releases/download/v1.0.1/flow_Linux_arm64.tar.gz"
      sha256 "0a331425f75d901c086028d01f2ab32c0a3fc9c32209a211b3c08ca2324581c3"

      def install
        bin.install "flow"
      end
    end
  end
end
