# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowTracker < Formula
  desc "Efortless time tracking in your terminal"
  homepage "https://github.com/TristanSch1/flow"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TristanSch1/flow/releases/download/v0.1.0/flow_Darwin_x86_64.tar.gz"
      sha256 "d16042546685b9fcb0357e938f9a902776360b07b3d7fff6b4ee87d7b64c742a"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TristanSch1/flow/releases/download/v0.1.0/flow_Darwin_arm64.tar.gz"
      sha256 "dd34a59d3424384fa8c84f10d1115786c6a66fdacb2a0d950e9ec22bb6183777"

      def install
        bin.install "flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TristanSch1/flow/releases/download/v0.1.0/flow_Linux_x86_64.tar.gz"
      sha256 "1ca102dbf07ccaa35df91850308c0d053c680f0f87addcf0423ae92c9ee1dbac"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TristanSch1/flow/releases/download/v0.1.0/flow_Linux_arm64.tar.gz"
      sha256 "eeba295fc92dfdb58b1c533017cae9991b94ead58ca8013158b1cc313a33d2de"

      def install
        bin.install "flow"
      end
    end
  end
end
