# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowTracker < Formula
  desc "Efortless time tracking in your terminal"
  homepage "https://github.com/TristanSch1/flow"
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/TristanShz/flow/releases/download/v1.1.0/flow_Darwin_x86_64.tar.gz"
      sha256 "3ccd26b76712b9433b82696f032d6f5faff4690ad56d90709e86e3ff86fc0d6a"

      def install
        bin.install "flow"
      end
    end
    on_arm do
      url "https://github.com/TristanShz/flow/releases/download/v1.1.0/flow_Darwin_arm64.tar.gz"
      sha256 "9b580b4fe170896957c4e248763dca633e537d108d198a7daa43a0b632e42f18"

      def install
        bin.install "flow"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TristanShz/flow/releases/download/v1.1.0/flow_Linux_x86_64.tar.gz"
        sha256 "1b000651d64ede8b8694f702f4c8743d8fcd89edae3ec54146c2b35e3d8f1d03"

        def install
          bin.install "flow"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TristanShz/flow/releases/download/v1.1.0/flow_Linux_arm64.tar.gz"
        sha256 "d8fcc5c387efc438e3e8509ff867b65ccd1369ca608b5bee8d316994a3c2490f"

        def install
          bin.install "flow"
        end
      end
    end
  end
end
